package CollectionsPrachiMam;
import java.util.*;
public class StackQuestion8_1 {
	public static void main(String[] args) {
		Stack s=new Stack();
		s.push("A");
		s.push("B");
		s.push("C");
		s.push("D");
		s.push("E");
		s.push("F");
		s.push("G");
		s.push("H");
		s.push("I");
		s.push("J");
		s.push("K");
		s.push("L");
		s.push("M");
		s.push("N");
		s.push("O");
		s.push("P");
		s.push("Q");
		s.push("R");
		s.push("S");
		s.push("T");
		s.push("U");
		s.push("V");
		s.push("W");
		s.push("X");
		s.push("Y");
		s.push("Z");
		Object o1=s.pop();
		Object o2=s.pop();
		Object o3=s.pop();
		Object o4=s.pop();
		Object o5=s.pop();
		Object o6=s.pop();
		Object o7=s.pop();
		Object o8=s.pop();
		Object o9=s.pop();
		Object o10=s.pop();
		Object o11=s.pop();
		Object o12=s.pop();
		Object o13=s.pop();
		Object o14=s.pop();
		Object o15=s.pop();
		Object o16=s.pop();
		Object o17=s.pop();
		Object o18=s.pop();
		Object o19=s.pop();
		Object o20=s.pop();
		Object o21=s.pop();
		Object o22=s.pop();
		Object o23=s.pop();
		Object o24=s.pop();
		Object o25=s.pop();
		Object o26=s.pop();
		

		System.out.println(o1);
		System.out.println(o2);
		System.out.println(o3);
		System.out.println(o4);
		System.out.println(o5);
		System.out.println(o6);
		System.out.println(o7);
		System.out.println(o8);
		System.out.println(o9);
		System.out.println(o10);
		System.out.println(o11);
		System.out.println(o12);
		System.out.println(o13);
		System.out.println(o14);
		System.out.println(o15);
		System.out.println(o16);
		System.out.println(o17);
		System.out.println(o18);
		System.out.println(o19);
		System.out.println(o20);
		System.out.println(o21);
		System.out.println(o22);
		System.out.println(o23);
		System.out.println(o24);
		System.out.println(o25);
		System.out.println(o26);
		
		System.out.println(s);
		
		Stack s1=new Stack();
		s1.push("Z");
		s1.push("Y");
		s1.push("X");
		s1.push("W");
		s1.push("V");
		s1.push("U");
		s1.push("T");
		s1.push("S");
		s1.push("R");
		s1.push("Q");
		s1.push("P");
		s1.push("O");
		s1.push("N");
		s1.push("M");
		s1.push("L");
		s1.push("K");
		s1.push("J");
		s1.push("I");
		s1.push("H");
		s1.push("G");
		s1.push("F");
		s1.push("E");
		s1.push("D");
		s1.push("C");
		s1.push("B");
		s1.push("A");
		Object ob1=s1.pop();
		Object ob2=s1.pop();
		Object ob3=s1.pop();
		Object ob4=s1.pop();
		Object ob5=s1.pop();
		Object ob6=s1.pop();
		Object ob7=s1.pop();
		Object ob8=s1.pop();
		Object ob9=s1.pop();
		Object ob10=s1.pop();
		Object ob11=s1.pop();
		Object ob12=s1.pop();
		Object ob13=s1.pop();
		Object ob14=s1.pop();
		Object ob15=s1.pop();
		Object ob16=s1.pop();
		Object ob17=s1.pop();
		Object ob18=s1.pop();
		Object ob19=s1.pop();
		Object ob20=s1.pop();
		Object ob21=s1.pop();
		Object ob22=s1.pop();
		Object ob23=s1.pop();
		Object ob24=s1.pop();
		Object ob25=s1.pop();
		Object ob26=s1.pop();
		

		System.out.println(ob1);
		System.out.println(ob2);
		System.out.println(ob3);
		System.out.println(ob4);
		System.out.println(ob5);
		System.out.println(ob6);
		System.out.println(ob7);
		System.out.println(ob8);
		System.out.println(ob9);
		System.out.println(ob10);
		System.out.println(ob11);
		System.out.println(ob12);
		System.out.println(ob13);
		System.out.println(ob14);
		System.out.println(ob15);
		System.out.println(ob16);
		System.out.println(ob17);
		System.out.println(ob18);
		System.out.println(ob19);
		System.out.println(ob20);
		System.out.println(ob21);
		System.out.println(ob22);
		System.out.println(ob23);
		System.out.println(ob24);
		System.out.println(ob25);
		System.out.println(ob26);
		
		System.out.println(s1);
	}
}
		//s.push("A,B,C,D,E,F");
		/*s.push("A");
		s.push("B");
		s.push("C");
		s.push("D");
		s.push("E");
		s.push("F");
		s.pop();
		s.pop();
		s.pop();
		s.pop();
		s.pop();*/

		//System.out.println(s);
		//Stack s1=new Stack();
		//s1.push("A,B,C,D,E,F");
		/*s1.push("A");
		s1.push("B");
		s1.push("C");
		s1.push("D");
		s1.push("E");
		s1.push("F");

		s1.pop();
		System.out.println(s1);
	}

}*/
